/* tslint:disable */
/* eslint-disable */
/**
 * TOTECO API
 * API to manage publications about products (coffee, tea or toast) like a social media. The idea is to create a community that publishes photos of their toasts with coffee or tea adding the price and being able to rate the products and the establishments.
 *
 * OpenAPI spec version: 1.0
 * Contact: a25540@svalero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 
 *
 * @export
 * @interface EstablishmentDTO
 */
export interface EstablishmentDTO {

    /**
     * @type {string}
     * @memberof EstablishmentDTO
     * @example Casa Paco
     */
    name?: string;

    /**
     * @type {Location}
     * @memberof EstablishmentDTO
     */
    location?: Location;

    /**
     * @type {boolean}
     * @memberof EstablishmentDTO
     * @example false
     */
    open?: boolean;
}
