/* tslint:disable */
/* eslint-disable */
/**
 * TOTECO SERVICE
 * Toteco API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {

    /**
     * @type {string}
     * @memberof LoginRequest
     */
    username?: string;

    /**
     * @type {string}
     * @memberof LoginRequest
     */
    password?: string;
}
