/* tslint:disable */
/* eslint-disable */
/**
 * Toteco Service
 * Toteco API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * Menu transfer object
 *
 * @export
 * @interface MenuDTO
 */
export interface MenuDTO {

    /**
     * @type {number}
     * @memberof MenuDTO
     */
    price: number;

    /**
     * @type {number}
     * @memberof MenuDTO
     */
    score: number;
}
