/* tslint:disable */
/* eslint-disable */
/**
 * TOTECO API
 * API to manage publications about products (coffee, tea or toast) like a social media. The idea is to create a community that publishes photos of their toasts with coffee or tea adding the price and being able to rate the products and the establishments.
 *
 * OpenAPI spec version: 1.0
 * Contact: a25540@svalero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Menu } from "./menu";
import { Publication } from "./publication";
import { Type } from "./type";

/**
 * 
 *
 * @export
 * @interface Product
 */
export interface Product {

    /**
     * @type {number}
     * @memberof Product
     * @example 0
     */
    id?: number;

    /**
     * @type {Type}
     * @memberof Product
     */
    type?: Type;

    /**
     * @type {string}
     * @memberof Product
     * @example 04-03-2022
     */
    date?: string;

    /**
     * @type {number}
     * @memberof Product
     * @example 3.4
     */
    price?: number;

    /**
     * @type {number}
     * @memberof Product
     * @example 4.3
     */
    score?: number;

    /**
     * @type {Menu}
     * @memberof Product
     */
    menu?: Menu;

    /**
     * @type {Publication}
     * @memberof Product
     */
    publication?: Publication;
}
