/* tslint:disable */
/* eslint-disable */
/**
 * TOTECO API
 * API to manage publications about products (coffee, tea or toast) like a social media. The idea is to create a community that publishes photos of their toasts with coffee or tea adding the price and being able to rate the products and the establishments.
 *
 * OpenAPI spec version: 1.0
 * Contact: a25540@svalero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Establishment } from "./establishment";
import { User } from "./user";

/**
 * 
 *
 * @export
 * @interface Publication
 */
export interface Publication {

    /**
     * @type {number}
     * @memberof Publication
     * @example 0
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Publication
     * @example 03-05-2022
     */
    date?: string;

    /**
     * @type {number}
     * @memberof Publication
     * @example 3.4
     */
    totalPrice?: number;

    /**
     * @type {number}
     * @memberof Publication
     * @example 2.5
     */
    totalScore?: number;

    /**
     * @type {string}
     * @memberof Publication
     */
    photo?: string;

    /**
     * @type {User}
     * @memberof Publication
     */
    user?: User;

    /**
     * @type {Establishment}
     * @memberof Publication
     */
    establishment?: Establishment;
}
