/* tslint:disable */
/* eslint-disable */
/**
 * Toteco Service
 * Toteco API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * Publication transfer object
 *
 * @export
 * @interface PublicationDTO
 */
export interface PublicationDTO {

    /**
     * @type {Array<string>}
     * @memberof PublicationDTO
     */
    photo?: Array<string>;

    /**
     * @type {string}
     * @memberof PublicationDTO
     */
    userId: string;

    /**
     * @type {string}
     * @memberof PublicationDTO
     */
    establishmentId: string;

    /**
     * @type {number}
     * @memberof PublicationDTO
     */
    totalScore: number;

    /**
     * @type {number}
     * @memberof PublicationDTO
     */
    totalPrice: number;
}
