/* tslint:disable */
/* eslint-disable */
/**
 * Toteco Service
 * Toteco API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Publication } from './publication';

/**
 * 
 *
 * @export
 * @interface UserModel
 */
export interface UserModel {

    /**
     * @type {string}
     * @memberof UserModel
     */
    id?: string;

    /**
     * @type {string}
     * @memberof UserModel
     */
    username: string;

    /**
     * @type {string}
     * @memberof UserModel
     */
    name: string;

    /**
     * @type {string}
     * @memberof UserModel
     */
    surname: string;

    /**
     * @type {number}
     * @memberof UserModel
     */
    birthDate: number;

    /**
     * @type {string}
     * @memberof UserModel
     */
    email: string;

    /**
     * @type {string}
     * @memberof UserModel
     */
    password: string;

    /**
     * @type {number}
     * @memberof UserModel
     */
    created?: number;

    /**
     * @type {number}
     * @memberof UserModel
     */
    modified?: number;

    /**
     * @type {boolean}
     * @memberof UserModel
     */
    active: boolean;

    /**
     * @type {number}
     * @memberof UserModel
     */
    moneySpent?: number;

    /**
     * @type {number}
     * @memberof UserModel
     */
    publicationsNumber?: number;

    /**
     * @type {string}
     * @memberof UserModel
     */
    role: string;

    /**
     * @type {number}
     * @memberof UserModel
     */
    recoveryCode?: number;

    /**
     * @type {Array<Publication>}
     * @memberof UserModel
     */
    publications?: Array<Publication>;
}
