/* tslint:disable */
/* eslint-disable */
/**
 * TOTECO SERVICE
 * Toteco API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {string}
     * @memberof User
     */
    id?: string;

    /**
     * @type {string}
     * @memberof User
     */
    username?: string;

    /**
     * @type {string}
     * @memberof User
     */
    name?: string;

    /**
     * @type {string}
     * @memberof User
     */
    surname?: string;

    /**
     * @type {number}
     * @memberof User
     */
    birthDate?: number;

    /**
     * @type {string}
     * @memberof User
     */
    email?: string;

    /**
     * @type {string}
     * @memberof User
     */
    password?: string;

    /**
     * @type {number}
     * @memberof User
     */
    created?: number;

    /**
     * @type {number}
     * @memberof User
     */
    updated?: number;

    /**
     * @type {boolean}
     * @memberof User
     */
    isActive?: boolean;

    /**
     * @type {number}
     * @memberof User
     */
    moneySpent?: number;

    /**
     * @type {number}
     * @memberof User
     */
    publicationsNumber?: number;

    /**
     * @type {string}
     * @memberof User
     */
    role?: string;

    /**
     * @type {number}
     * @memberof User
     */
    recoveryCode?: number;
}
