/* tslint:disable */
/* eslint-disable */
/**
 * TOTECO SERVICE
 * Toteco API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/establishments-api';
export * from './apis/login-api';
export * from './apis/menus-api';
export * from './apis/products-api';
export * from './apis/publications-api';
export * from './apis/users-api';

